repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: 3e8a8703264a2f4a69428a0aa4dcb512790b2c8c # frozen: v6.0.0
    hooks:
      - id: check-added-large-files
      - id: check-ast
      - id: check-builtin-literals
      - id: check-case-conflict
      - id: check-json
      - id: check-yaml
        args: [--allow-multiple-documents]
      - id: debug-statements
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: trailing-whitespace

  - repo: https://github.com/rbubley/mirrors-prettier
    rev: b25652612a4a3c1da8caccfca9af661db56b2c07 # frozen: v3.8.2
    hooks:
      - id: prettier
        types_or: [yaml, markdown, javascript]
        args: [--prose-wrap=preserve]

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: b831c3dc5d27d9da294ae4e915773b99aa24a7c5 # frozen: v0.15.10
    hooks:
      - id: ruff
        args:
          [
            "--fix",
            "--show-fixes",
            "--exit-non-zero-on-fix",
            "--target-version=py38",
          ]
      - id: ruff-format

  - repo: https://github.com/woodruffw/zizmor-pre-commit
    rev: a4727cbbcd26d7098e96b9cb738169b59711ae51 # frozen: v1.24.1
    hooks:
      - id: zizmor
        args: [--pedantic, --fix=safe]

ci:
  # This ensures that PRs aren't autofixed by the bot, and rather you
  # call the bot to make the fix
  autofix_prs: false
