repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: 3e8a8703264a2f4a69428a0aa4dcb512790b2c8c # frozen: v6.0.0
    hooks:
      - id: check-added-large-files
      - id: check-ast
      - id: check-builtin-literals
      - id: check-case-conflict
      - id: check-json
      - id: check-yaml
        args: [--allow-multiple-documents]
      - id: debug-statements
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: trailing-whitespace

  - repo: https://github.com/rbubley/mirrors-prettier
    rev: 0ee178619d696787ca73d210cc191d720868c631 # frozen: v3.9.6
    hooks:
      - id: prettier
        types_or: [yaml, markdown, javascript]
        args: [--prose-wrap=preserve]

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: 39d9ac5938dadb73df0564a45f163e25ff9fa6e2 # frozen: v0.16.1
    hooks:
      - id: ruff
        args:
          [
            "--fix",
            "--show-fixes",
            "--exit-non-zero-on-fix",
            "--target-version=py38",
          ]
      - id: ruff-format

  - repo: https://github.com/woodruffw/zizmor-pre-commit
    rev: 451b56af716f9f0d0c2b816503a3fd0cf8b036fa # frozen: v1.29.0
    hooks:
      - id: zizmor
        args: [--pedantic, --fix=safe]

ci:
  # This ensures that PRs aren't autofixed by the bot, and rather you
  # call the bot to make the fix
  autofix_prs: false
