repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: 3e8a8703264a2f4a69428a0aa4dcb512790b2c8c # frozen: v6.0.0
    hooks:
      - id: check-added-large-files
      - id: check-ast
      - id: check-builtin-literals
      - id: check-case-conflict
      - id: check-json
      - id: check-yaml
        args: [--allow-multiple-documents]
      - id: debug-statements
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: trailing-whitespace

  - repo: https://github.com/rbubley/mirrors-prettier
    rev: 06507ab9500d4a9919b5ebd76d9d5b7074f15c1f # frozen: v3.8.4
    hooks:
      - id: prettier
        types_or: [yaml, markdown, javascript]
        args: [--prose-wrap=preserve]

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: 3b3f7c3f57fe9925356faf5fe6230835138be230 # frozen: v0.15.17
    hooks:
      - id: ruff
        args:
          [
            "--fix",
            "--show-fixes",
            "--exit-non-zero-on-fix",
            "--target-version=py38",
          ]
      - id: ruff-format

  - repo: https://github.com/woodruffw/zizmor-pre-commit
    rev: 9257c6050c0261b8c57e712f632dc4a8010109a9 # frozen: v1.25.2
    hooks:
      - id: zizmor
        args: [--pedantic, --fix=safe]

ci:
  # This ensures that PRs aren't autofixed by the bot, and rather you
  # call the bot to make the fix
  autofix_prs: false
